[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net blob:; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; connect-src 'self' https://cdn.jsdelivr.net https://tinyurl.com https://is.gd https://*.supabase.co https://threejs.org https://raw.githubusercontent.com; frame-src 'self' https://github.com; font-src 'self' data: https://cdn.jsdelivr.net https://fonts.gstatic.com; img-src 'self' data: https:; worker-src 'self' blob:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200