[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https://cdn.jsdelivr.net https://tinyurl.com https://is.gd https://*.supabase.co; frame-src 'self' https://github.com; font-src 'self' data:; img-src 'self' data: https:;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200